name: 'connvertpay'
services:
  postgres:
    image: postgres:16.3-alpine
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=connvertpay-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
